//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_PetSupply.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public int Id { get; set; }
        public int Id_Mascota { get; set; }
        public string Descripcion_Servicio { get; set; }
        public int Precio { get; set; }
        public int Id_Horario { get; set; }
    
        public virtual Horario Horario { get; set; }
        public virtual Mascota Mascota { get; set; }
    }
}
